### Average baseline for bikes dataset

In [1]:
# get the metrics for a model that only predicts the average price

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import csv

In [2]:
im_inds = []
im_names = []
im_prices = np.zeros(21843)
with open('../datasets/bikes_filtered.csv', 'r') as f:
        datareader = csv.reader(f)
        for i, line in enumerate(datareader):
            im_inds.append(line[0])
            im_names.append(line[1])
            im_prices[i] = int(line[2])

In [3]:
avg = np.average(im_prices)

In [4]:
avg

1682.3578720871676

In [5]:
predicted = np.full((21843, ), avg)

In [6]:
train_inds = np.load('bikes_train_indices.npy')
test_inds = np.load('bikes_test_indices.npy')

In [7]:
predicted = predicted[test_inds]
im_prices = im_prices[test_inds]

In [8]:
mean_squared_error(im_prices, predicted)

3276787.7276074942

In [9]:
mean_absolute_error(im_prices, predicted)

1318.5307114396887

In [10]:
r2_score(im_prices, predicted)

-0.00016387045703925018

### Average baseline for cars dataset

In [7]:
im_inds = []
im_names = []
im_prices = np.zeros(1478)
with open('../datasets/cars_filtered.csv', 'r') as f:
        datareader = csv.reader(f)
        for i, line in enumerate(datareader):
            im_inds.append(line[0])
            im_names.append(line[1])
            im_prices[i] = int(line[3])

In [8]:
avg = np.average(im_prices)

In [11]:
avg

60885.625845737486

In [12]:
predicted = np.full((1478, ), avg)

In [13]:
train_inds = np.load('cars_train_indices.npy')
test_inds = np.load('cars_test_indices.npy')

In [14]:
predicted = predicted[test_inds]
im_prices = im_prices[test_inds]

In [15]:
mean_squared_error(im_prices, predicted)

5812600017.6289692

In [16]:
mean_absolute_error(im_prices, predicted)

44410.57105575654

In [17]:
r2_score(im_prices, predicted)

-8.0765636178981026e-07

### Average baselines for classification

In [1]:
import csv
from sklearn import metrics
import numpy as np

In [2]:
data_path = "../datasets/bikes_im/"

im_inds = []
im_names = []
im_prices = []
im_labels = []
with open('../datasets/bikes_classified.csv', 'r') as f:
        datareader = csv.reader(f)
        for line in datareader:
            im_inds.append(line[0])
            im_names.append(line[1])
            im_prices.append(line[2])
            im_labels.append(line[3])

In [3]:
# Use same train-test split as other models
train_indices = np.load("bikes_train_indices.npy")
test_indices = np.load("bikes_test_indices.npy")
print(train_indices.shape)
print(test_indices.shape)

(19658,)
(2185,)


In [7]:
# generate random classes out of '25', '50', '75'
labels = np.array(im_labels)
labels_test = labels[test_indices]
predictions = np.random.choice(['25', '50', '75'], 2185)

In [8]:
print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

Classification report:
             precision    recall  f1-score   support

        100       0.00      0.00      0.00       496
         25       0.27      0.33      0.30       596
         50       0.26      0.33      0.29       563
         75       0.23      0.32      0.27       530

avg / total       0.20      0.25      0.22      2185


Confusion matrix:
[[  0 150 170 176]
 [  0 198 195 203]
 [  0 187 184 192]
 [  0 192 168 170]]


/Users/stevenchen/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [9]:
data_path = "../datasets/cars_im/"

im_inds = []
im_names = []
im_prices = []
im_labels = []
with open('../datasets/cars_classified.csv', 'r') as f:
        datareader = csv.reader(f)
        for line in datareader:
            im_inds.append(line[0])
            im_names.append(line[2])
            im_prices.append(line[3])
            im_labels.append(line[4])

In [10]:
# Use same train-test split as other models
train_indices = np.load("cars_train_indices.npy")
test_indices = np.load("cars_test_indices.npy")
print(train_indices.shape)
print(test_indices.shape)

(1330,)
(147,)


In [13]:
# generate random classes out of '25', '50', '75'
labels = np.array(im_labels)
labels_test = labels[test_indices]
predictions = np.random.choice(['20', '40', '60', '80'], 147)

In [14]:
print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

Classification report:
             precision    recall  f1-score   support

        100       0.00      0.00      0.00        29
         20       0.38      0.39      0.38        36
         40       0.19      0.21      0.20        34
         60       0.14      0.20      0.16        25
         80       0.14      0.22      0.17        23

avg / total       0.18      0.21      0.19       147


Confusion matrix:
[[ 0  5 12  7  5]
 [ 0 14  5 10  7]
 [ 0  9  7 10  8]
 [ 0  3  5  5 12]
 [ 0  6  8  4  5]]


/Users/stevenchen/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
