In [1]:
import yaml
import csv
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
data_path = "../datasets/cars_im/"

im_inds = []
im_names = []
im_prices = []
im_labels = []
with open('../datasets/cars_classified.csv', 'r') as f:
        datareader = csv.reader(f)
        for line in datareader:
            im_inds.append(line[0])
            im_names.append(line[2])
            im_prices.append(line[3])
            im_labels.append(line[4])

data_cnn_features = np.load("car_linreg_cnn_pca_features.npy")
print(data_cnn_features.shape)

(1478, 256)


In [3]:
# Use same train-test split as other models
train_indices = np.load("cars_train_indices.npy")
test_indices = np.load("cars_test_indices.npy")
print(train_indices.shape)
print(test_indices.shape)

(1330,)
(147,)


In [4]:
features_train = data_cnn_features[train_indices]
features_test = data_cnn_features[test_indices]
labels = np.array(im_labels)
labels_train = labels[train_indices]
labels_test = labels[test_indices]

In [5]:
classifier = svm.SVC(gamma=0.001)
classifier.fit(features_train, labels_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
predictions = classifier.predict(features_test)

In [7]:
print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

Classification report:
             precision    recall  f1-score   support

        100       0.90      0.90      0.90        29
         20       0.97      0.78      0.86        36
         40       0.67      0.88      0.76        34
         60       0.68      0.68      0.68        25
         80       0.84      0.70      0.76        23

avg / total       0.81      0.80      0.80       147


Confusion matrix:
[[26  0  1  1  1]
 [ 0 28  7  1  0]
 [ 0  1 30  3  0]
 [ 1  0  5 17  2]
 [ 2  0  2  3 16]]
