In [28]:
import yaml
import csv
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split
import numpy as np


In [24]:
data_path = "../datasets/bikes_im/"

thresholds = {"cheap": 0, "average": 500, "expensive":1000}

im_inds = []
im_names = []
im_prices = []
with open('../datasets/bikes_filtered.csv', 'r') as f:
        datareader = csv.reader(f)
        for line in datareader:
            im_inds.append(line[0])
            im_names.append(line[1])
            im_prices.append(line[2])

data_cnn_features = np.load("bikes_cnn_pca_features.npy")
data_labels = []
for i in im_prices:
    label = ""
    for value, key in sorted(((v,k) for k,v in thresholds.items())):
        if (float(i)-float(value)) < 0:
            continue
        label = key
    data_labels.append(label)

In [25]:
features_train, features_test, labels_train, labels_test = train_test_split(data_cnn_features, data_labels, test_size=0.1)

In [26]:
classifier = svm.SVC(gamma=0.001)
classifier.fit(features_train, labels_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
predictions = classifier.predict(features_test)

In [29]:
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

    average       0.95      0.28      0.43       575
      cheap       0.97      0.28      0.44       586
  expensive       0.55      1.00      0.71      1024

avg / total       0.77      0.62      0.56      2185


Confusion matrix:
[[ 160    6  409]
 [   3  166  417]
 [   5    0 1019]]
