In [2]:
import yaml
import csv
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split
import numpy as np


In [13]:
data_path = "../datasets/cars_im/"

im_inds = []
im_names = []
im_prices = []
im_labels = []
with open('../datasets/cars_classified.csv', 'r') as f:
        datareader = csv.reader(f)
        for line in datareader:
            im_inds.append(line[0])
            im_names.append(line[2])
            im_prices.append(line[3])
            im_labels.append(line[4])

data_cnn_features = np.load("car_linreg_cnn_pca_features.npy")
print(data_cnn_features.shape)

(1478, 256)


In [ ]:
'''
#Depreciated, using new bikes_classified CSV now
data_labels = []
thresholds = {"cheap": 0, "average": 500, "expensive":1000}
for i in im_prices:
    label = ""
    for value, key in sorted(((v,k) for k,v in thresholds.items())):
        if (float(i)-float(value)) < 0:
            continue
        label = key
    data_labels.append(label)
'''

In [14]:
# Use same train-test split as other models
train_indices = np.load("cars_train_indices.npy")
test_indices = np.load("cars_test_indices.npy")
print(train_indices.shape)
print(test_indices.shape)

(1330,)
(147,)


In [16]:
features_train = data_cnn_features[train_indices]
features_test = data_cnn_features[test_indices]
labels = np.array(im_labels)
labels_train = labels[train_indices]
labels_test = labels[test_indices]

In [17]:
classifier = svm.SVC(gamma=0.001)
classifier.fit(features_train, labels_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [18]:
predictions = classifier.predict(features_test)

In [19]:
print("Classification report:\n%s\n"
      % (metrics.classification_report(labels_test, predictions)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(labels_test, predictions))

Classification report:
             precision    recall  f1-score   support

        100       0.87      0.93      0.90        29
         20       0.97      0.81      0.88        36
         40       0.69      0.91      0.78        34
         60       0.71      0.60      0.65        25
         80       0.90      0.78      0.84        23

avg / total       0.83      0.82      0.82       147


Confusion matrix:
[[27  0  1  1  0]
 [ 0 29  6  1  0]
 [ 0  1 31  2  0]
 [ 1  0  7 15  2]
 [ 3  0  0  2 18]]
